/**
 * Duplicates all programme_sessions for a given block, creating the next block.
 *
 * New rows get:
 *   block_number    = blockNumber + 1
 *   week_number     = original week_number + 2
 *   scheduled_date  = original scheduled_date + 14 days (if set)
 *   status          = 'planned'
 *   sessions_planned_id = null
 *   id              = auto-generated by Supabase
 *
 * All other fields (exercise selections, sets, reps, etc.) are copied exactly.
 *
 * @param {string} programmeId   — active programme UUID
 * @param {number} blockNumber   — the block to duplicate (1-based)
 * @param {object} supabase      — Supabase client instance
 * @returns {Promise<{ success: boolean, count?: number, error?: string }>}
 */
export async function duplicateBlock(programmeId, blockNumber, supabase) {
  try {
    // 1. Fetch all sessions for this block
    const { data: sourceSessions, error: fetchError } = await supabase
      .from('programme_sessions')
      .select('*')
      .eq('programme_id', programmeId)
      .eq('block_number', blockNumber)
      .order('week_number', { ascending: true })
      .order('session_number', { ascending: true })

    if (fetchError) return { success: false, error: fetchError.message }
    if (!sourceSessions?.length) return { success: true, count: 0 }

    // 2. Build duplicate rows
    const newRows = sourceSessions.map(({
      id,                  // omit — DB generates new UUID
      created_at,          // omit — DB sets this
      sessions_planned_id, // clear — not yet linked to planner
      scheduled_date,
      status,
      block_number: _bn,
      week_number,
      ...rest
    }) => ({
      ...rest,
      programme_id:        programmeId,
      block_number:        blockNumber + 1,
      week_number:         week_number + 2,
      status:              'planned',
      sessions_planned_id: null,
      scheduled_date:      scheduled_date ? shiftDate(scheduled_date, 14) : null,
    }))

    // 3. Insert
    const { data, error } = await supabase
      .from('programme_sessions')
      .insert(newRows)
      .select('id')

    if (error) return { success: false, error: error.message }
    return { success: true, count: (data ?? []).length }

  } catch (err) {
    console.error('[duplicateBlock] threw:', err.message)
    return { success: false, error: err.message }
  }
}

/**
 * Adds `days` days to a YYYY-MM-DD string using local-time arithmetic
 * to avoid UTC midnight drift.
 */
function shiftDate(dateStr, days) {
  const [y, m, d] = dateStr.split('-').map(Number)
  const date = new Date(y, m - 1, d)
  date.setDate(date.getDate() + days)
  const ny = date.getFullYear()
  const nm = String(date.getMonth() + 1).padStart(2, '0')
  const nd = String(date.getDate()).padStart(2, '0')
  return `${ny}-${nm}-${nd}`
}
