import { supabase } from '../lib/supabase'

/**
 * Duplicates all programme_sessions in a given block, shifting them forward
 * by 14 days / 2 weeks to create the repeated block.
 *
 * New rows get:
 *   block_number  = blockNumber + 1
 *   week_number   = original week_number + 2
 *   scheduled_date (if set) shifted +14 days
 *   status        = 'planned'
 *   sessions_planned_id = null  (not yet linked to planner)
 *   id            = auto-generated by Supabase
 *
 * All other fields (exercise selection, sets, reps, purpose_note, etc.) are
 * copied exactly so the user repeats the identical training stimulus.
 *
 * @param {string} programmeId  — active programme UUID
 * @param {number} blockNumber  — the block to duplicate (1-based)
 * @returns {Promise<{ data: Array|null, error: object|null }>}
 */
export async function duplicateBlock(programmeId, blockNumber) {
  try {
    // Fetch all sessions for this block
    const { data: sourceSessions, error: fetchError } = await supabase
      .from('programme_sessions')
      .select('*')
      .eq('programme_id', programmeId)
      .eq('block_number', blockNumber)
      .order('week_number', { ascending: true })
      .order('session_number', { ascending: true })

    if (fetchError) return { data: null, error: fetchError }
    if (!sourceSessions?.length) return { data: [], error: null }

    const newRows = sourceSessions.map(({
      id,                  // omit — DB generates new UUID
      created_at,          // omit — DB sets this
      sessions_planned_id, // clear — not yet linked to planner
      scheduled_date,      // shift +14 days if set, otherwise null
      status,              // reset to planned
      block_number: _bn,   // override below
      week_number,         // override below
      ...rest
    }) => ({
      ...rest,
      programme_id:        programmeId,
      block_number:        blockNumber + 1,
      week_number:         week_number + 2,
      status:              'planned',
      sessions_planned_id: null,
      scheduled_date:      scheduled_date
        ? shiftDate(scheduled_date, 14)
        : null,
    }))

    const { data, error } = await supabase
      .from('programme_sessions')
      .insert(newRows)
      .select()

    return { data: data ?? null, error: error ?? null }
  } catch (err) {
    console.error('[duplicateBlock] threw:', err.message)
    return { data: null, error: err }
  }
}

/**
 * Adds `days` days to a YYYY-MM-DD date string and returns a new YYYY-MM-DD string.
 * Uses local-time date arithmetic to avoid UTC midnight drift.
 */
function shiftDate(dateStr, days) {
  const [y, m, d] = dateStr.split('-').map(Number)
  const date = new Date(y, m - 1, d)
  date.setDate(date.getDate() + days)
  const ny = date.getFullYear()
  const nm = String(date.getMonth() + 1).padStart(2, '0')
  const nd = String(date.getDate()).padStart(2, '0')
  return `${ny}-${nm}-${nd}`
}
