// alongside_exercises seeding script
// Run with: node scripts/seed_alongside_exercises.js
// Requires VITE_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in .env

import { createClient } from '@supabase/supabase-js'
import { readFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const envPath = join(__dirname, '..', '.env')
const envVars = {}
try {
  const envFile = readFileSync(envPath, 'utf8')
  for (const line of envFile.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eq = trimmed.indexOf('=')
    if (eq === -1) continue
    envVars[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim()
  }
} catch { /* .env not found — rely on real env */ }

const SUPABASE_URL     = envVars.VITE_SUPABASE_URL     || process.env.VITE_SUPABASE_URL
const SUPABASE_SERVICE = envVars.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY

if (!SUPABASE_URL || !SUPABASE_SERVICE) {
  console.error('Missing VITE_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY')
  process.exit(1)
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE)

const strengthEx = [
  // PRE-ACTIVATION / VERY LOW THRESHOLD
  {n:"Glute Tensing (Lying)",p:"Glute Pre-Activation",t:1,s:"Lower",e:"None",b:true,lb:false,c:"",start:"Lie on back, knees bent, feet flat, arms at sides.",move:"Gently tense both glutes as if trying to hold a coin between them; hold 5 sec, release; repeat.",avoid:"Holding breath or bracing so hard the lower back arches off the floor."},
  {n:"Inner Range Quads (Lying)",p:"Isolation/Knee Extension",t:1,s:"Lower",e:"None/Rolled Towel",b:true,lb:false,c:"",start:"Lie on back, rolled towel under one knee so it is slightly bent; other leg flat.",move:"Tighten the quad of the supported leg and straighten the knee fully, lifting the heel; hold 3 sec, lower.",avoid:"Jerking the movement or tilting the pelvis — isolate the quadriceps only."},
  {n:"Knee Flexion and Extension (Sitting)",p:"Isolation/Knee",t:1,s:"Lower",e:"Chair",b:true,lb:false,c:"",start:"Sit tall in a chair with feet flat on the floor.",move:"Slowly straighten one leg to near-full extension, hold 2 sec, lower under control; alternate legs.",avoid:"Kicking forcefully — the movement should be slow and controlled throughout."},
  // SQUAT
  {n:"Chair-Assisted Squat",p:"Squat",t:1,s:"Lower",e:"Chair",b:true,lb:true,c:"",start:"Stand before chair, feet shoulder-width, arms extended forward.",move:"Lower slowly until you feel the chair beneath you, then immediately drive through heels to stand.",avoid:"Dropping onto the chair — hover just above it to keep muscles working."},
  {n:"Bodyweight Squat",p:"Squat",t:1,s:"Lower",e:"None",b:true,lb:true,c:"",start:"Feet shoulder-width, toes slightly out, arms forward.",move:"Push knees out, sit back and down to parallel, drive through heels.",avoid:"Knees caving inward or heels lifting from the floor."},
  {n:"Wall Squat Hold",p:"Squat/Isometric",t:1,s:"Lower",e:"Wall",b:true,lb:true,c:"",start:"Back flat against wall, feet 2 feet forward, lower to 90° at knee and hip.",move:"Hold position breathing steadily; squeeze quads and keep knees tracking over toes.",avoid:"Knees caving inward or thighs dropping below parallel."},
  {n:"Goblet Squat",p:"Squat",t:1,s:"Lower",e:"DB/KB",b:true,lb:true,c:"",start:"Weight at chest, feet wider than hips, toes out.",move:"Squat deep with elbows tracking inside knees; drive through heels.",avoid:"Rounding upper back or losing upright torso."},
  {n:"Leg Press",p:"Squat",t:1,s:"Lower",e:"Machine",b:true,lb:true,c:"",start:"Feet hip-width on platform, back flat, slight knee bend.",move:"Lower to 90° at knee, press through full foot to extend.",avoid:"Locking knees at top or lower back peeling off pad."},
  {n:"KB Sumo Squat",p:"Squat/Wide Stance",t:1,s:"Lower",e:"Kettlebell",b:true,lb:true,c:"knee_pain",start:"Feet wider than shoulder-width, toes pointed out, KB hanging between legs in both hands.",move:"Sit straight down keeping chest tall and knees tracking over toes; drive through heels to stand.",avoid:"Knees caving inward or torso tipping forward — the wide stance keeps the KB from contacting the floor."},
  {n:"Box Squat",p:"Squat",t:2,s:"Lower",e:"Box",b:true,lb:true,c:"",start:"Stand before box, feet shoulder-width.",move:"Sit back onto box under control, pause briefly, drive through heels.",avoid:"Rocking forward or bouncing at the bottom."},
  {n:"Barbell Back Squat",p:"Squat",t:3,s:"Lower",e:"Barbell",b:true,lb:true,c:"spinal_load",start:"Bar on upper traps, brace core, feet shoulder-width.",move:"Break at hips and knees, descend to parallel, drive through heels.",avoid:"Knees caving or bar drifting forward off shelf."},
  {n:"Bulgarian Split Squat",p:"Squat/Single-leg",t:3,s:"Lower",e:"DB/Barbell",b:false,lb:true,c:"knee_pain",start:"Rear foot on bench, front foot forward, torso tall.",move:"Lower rear knee toward floor, front shin vertical, drive through front heel.",avoid:"Front knee tracking far past toe or torso collapsing."},
  {n:"KB Sumo Jump",p:"Plyometric/Squat",t:3,s:"Lower",e:"Kettlebell",b:true,lb:true,c:"knee_pain,lower_limb_injury",start:"Sumo stance, KB hanging between legs, quarter-squat loaded position.",move:"Explode upward through full hip and knee extension, allowing KB to rise; land softly back into sumo squat.",avoid:"Landing with stiff legs or allowing the KB to swing forward uncontrolled."},
  // HINGE
  {n:"Glute Bridge (Bodyweight)",p:"Hinge",t:1,s:"Lower",e:"None",b:true,lb:true,c:"",start:"Lie on back, knees bent, feet flat, arms at sides.",move:"Drive hips to ceiling squeezing glutes at top; lower under control.",avoid:"Hyperextending lower back or knees splaying out."},
  {n:"Hip Hinge (Bodyweight)",p:"Hinge",t:1,s:"Lower",e:"None",b:true,lb:true,c:"",start:"Feet hip-width, soft knee, hands on thighs.",move:"Push hips back, hands slide to knees; feel hamstring tension, drive hips forward.",avoid:"Rounding lower back or bending knees excessively."},
  {n:"Romanian Deadlift (DB)",p:"Hinge",t:1,s:"Lower",e:"Dumbbells",b:true,lb:true,c:"lower_back_flexion",start:"DBs in front of thighs, soft knee, neutral spine.",move:"Hinge at hip, lower DBs along legs to mid-shin; squeeze glutes to return.",avoid:"Rounding lower back or weight drifting away from legs."},
  {n:"Kettlebell Deadlift",p:"Hinge",t:1,s:"Lower",e:"Kettlebell",b:true,lb:true,c:"",start:"KB between feet, hinge to grip, neutral spine, chest proud.",move:"Drive through floor, hips and shoulders rise together, lock out tall.",avoid:"Jerking or rounding upper back at initiation."},
  {n:"Romanian Deadlift (BB)",p:"Hinge",t:2,s:"Lower",e:"Barbell",b:true,lb:true,c:"lower_back_flexion",start:"Bar at hip crease, soft knee, tall spine.",move:"Hinge, bar drags down thighs to mid-shin, drive hips forward to lockout.",avoid:"Bar drifting forward or lower back rounding at depth."},
  {n:"Trap Bar Deadlift",p:"Hinge",t:2,s:"Lower",e:"Trap Bar",b:true,lb:true,c:"",start:"Stand inside trap bar, grip handles, neutral spine.",move:"Push floor away, hips and shoulders rise together, full lockout.",avoid:"Hips shooting up before shoulders or hyperextending at lockout."},
  {n:"Hip Thrust (BB)",p:"Hinge/Glute",t:2,s:"Lower",e:"Bench/Barbell",b:true,lb:true,c:"lower_back_flexion",start:"Upper back on bench, bar across hips, feet flat.",move:"Drive hips to full extension, hard glute squeeze; lower under control.",avoid:"Hyperextending lower back at top."},
  {n:"Weighted Glute Bridge (KB)",p:"Hinge/Glute",t:2,s:"Lower",e:"Kettlebell",b:true,lb:true,c:"lower_back_flexion",start:"Lie on back, KB resting on hip crease, knees bent, feet flat.",move:"Drive hips to full extension squeezing glutes; lower under control.",avoid:"Hyperextending lower back or KB shifting off the hip during movement."},
  {n:"Bridge Leg Spreader",p:"Hinge/Glute/Abductor",t:2,s:"Lower",e:"None/Band",b:true,lb:true,c:"",start:"Lie on back, knees bent, feet hip-width, hips raised to bridge position.",move:"Hold bridge height and push knees outward against band resistance; return knees to hip-width.",avoid:"Hips dropping during the abduction — maintain bridge height throughout."},
  {n:"Conventional Deadlift",p:"Hinge",t:3,s:"Lower",e:"Barbell",b:true,lb:true,c:"lower_back_flexion",start:"Bar over mid-foot, grip outside legs, neutral spine.",move:"Legs push floor away, hips drive forward; bar stays against legs.",avoid:"Jerking off floor, bar drifting forward, losing upper back tension."},
  {n:"Single-Leg RDL",p:"Hinge/Single-leg",t:3,s:"Lower",e:"DB/KB",b:false,lb:true,c:"knee_pain,lower_back_flexion",start:"Balance on one leg, slight knee bend, weight in opposite hand.",move:"Hinge at hip, extend rear leg as counterbalance, lower weight to shin.",avoid:"Rotating hips open or rushing causing balance loss."},
  // PUSH — HORIZONTAL
  {n:"Wall Press-Up",p:"Push Horizontal",t:1,s:"Upper",e:"Wall",b:true,lb:false,c:"shoulder_pain",start:"Stand facing wall, hands at shoulder height and width.",move:"Lower chest to wall, press back to straight arms; maintain rigid body.",avoid:"Hips drifting forward or elbows flaring excessively wide."},
  {n:"Incline Press-Up",p:"Push Horizontal",t:1,s:"Upper",e:"Bench/Step",b:true,lb:false,c:"shoulder_pain",start:"Hands elevated on bench, full plank, body rigid.",move:"Lower chest to bench level, press back up; body stays in straight line.",avoid:"Hips sagging or neck dropping."},
  {n:"Press-Up (Knee)",p:"Push Horizontal",t:1,s:"Upper",e:"None",b:true,lb:false,c:"shoulder_pain,wrist_pain",start:"Hands shoulder-width, knees on floor, straight line from knee to head.",move:"Lower chest to floor, press back to straight arms.",avoid:"Hips sagging or elbows flaring."},
  {n:"Chest Press (Machine)",p:"Push Horizontal",t:1,s:"Upper",e:"Machine",b:true,lb:false,c:"shoulder_pain",start:"Adjust seat so handles are at mid-chest height; sit with back fully supported.",move:"Press handles forward to near-full extension; return under control with elbows tracking at 45°.",avoid:"Locking elbows at full extension or shoulders shrugging toward ears."},
  {n:"Press-Up (Full)",p:"Push Horizontal",t:2,s:"Upper",e:"None",b:true,lb:false,c:"shoulder_pain,wrist_pain",start:"Hands shoulder-width, full plank, rigid from head to heel.",move:"Lower chest to floor, elbows at 45°, press back explosively.",avoid:"Hips dropping or piking; elbows past 70°."},
  {n:"Dumbbell Bench Press",p:"Push Horizontal",t:2,s:"Upper",e:"DB/Bench",b:true,lb:false,c:"shoulder_pain",start:"Lie on bench, DBs at chest, feet flat.",move:"Press DBs up to full extension, lower under control.",avoid:"DBs drifting too wide or bouncing off chest."},
  {n:"Chest Fly (Machine)",p:"Push Horizontal/Isolation",t:2,s:"Upper",e:"Machine",b:true,lb:false,c:"shoulder_pain",start:"Sit upright, arms wide on pad handles, slight elbow bend.",move:"Bring arms together in front of chest in a wide hugging arc; return under control.",avoid:"Straightening elbows fully or allowing shoulders to roll forward at end range."},
  {n:"Monkey Grip Press-Up",p:"Push Horizontal",t:3,s:"Upper",e:"None",b:true,lb:false,c:"wrist_pain",start:"Full press-up position but on knuckles with a neutral wrist grip.",move:"Perform press-up maintaining neutral wrist throughout; lower and press.",avoid:"Rolling knuckles inward — keep the fist tight and wrists straight."},
  {n:"Barbell Bench Press",p:"Push Horizontal",t:3,s:"Upper",e:"Barbell/Bench",b:true,lb:false,c:"shoulder_pain",start:"Grip slightly wider than shoulder-width, bar over lower chest.",move:"Lower to chest under control, drive through full press to lockout.",avoid:"Bouncing bar or losing scapular retraction."},
  // PUSH — VERTICAL
  {n:"DB Shoulder Press (Seated)",p:"Push Vertical",t:1,s:"Upper",e:"Dumbbells",b:true,lb:false,c:"shoulder_pain,neck_pain",start:"Seated, DBs at shoulder height, elbows at 90°, back supported.",move:"Press overhead to full extension; lower under control.",avoid:"Flaring ribs or pushing with the lower back."},
  {n:"Shoulder Press (Machine)",p:"Push Vertical",t:1,s:"Upper",e:"Machine",b:true,lb:false,c:"shoulder_pain,neck_pain",start:"Adjust seat so handles are at shoulder height; back fully supported, core gently braced.",move:"Press handles overhead to near-full extension; lower under control.",avoid:"Shrugging shoulders or using the back to push through the sticking point."},
  {n:"DB Shoulder Press (Standing)",p:"Push Vertical",t:2,s:"Upper",e:"Dumbbells",b:true,lb:false,c:"shoulder_pain,lower_back_flexion",start:"Standing, DBs at shoulder height, core braced.",move:"Press overhead to full extension with slight forward arc at top.",avoid:"Leaning back excessively through the sticking point."},
  {n:"Landmine Shoulder Press",p:"Push Vertical",t:2,s:"Upper",e:"Barbell/Landmine",b:false,lb:false,c:"shoulder_pain",start:"Hold end of landmine barbell at shoulder height in one hand; stagger stance, brace core.",move:"Press the bar forward and up along its arc to full extension; lower under control; complete set then swap sides.",avoid:"Rotating the torso to assist the press — keep hips and shoulders square throughout."},
  {n:"KB Press (Rack Position)",p:"Push Vertical",t:2,s:"Upper",e:"Kettlebell",b:false,lb:false,c:"shoulder_pain",start:"KB in rack position at shoulder, elbow tucked, tight brace.",move:"Press bell overhead to full lockout; lower under control.",avoid:"Flaring the ribcage or pressing in front of the face."},
  {n:"KB Bottom-Up Press",p:"Push Vertical/Stability",t:3,s:"Upper",e:"Kettlebell",b:false,lb:false,c:"shoulder_pain,wrist_pain",start:"KB held bottom-up at shoulder height (bell above handle), elbow at 90°, tight grip.",move:"Press slowly overhead to lockout maintaining the inverted KB position; lower under control.",avoid:"Allowing the KB to tip — the instability demands constant wrist and shoulder activation."},
  {n:"Barbell Overhead Press",p:"Push Vertical",t:3,s:"Upper",e:"Barbell",b:true,lb:false,c:"shoulder_pain,spinal_load",start:"Bar at upper chest, grip slightly wider than shoulders, hard brace.",move:"Press overhead in slight S-curve, lock out over mid-foot.",avoid:"Excessive forward lean or pressing in front of face."},
  {n:"Lateral Raise",p:"Push Vertical/Isolation",t:2,s:"Upper",e:"DB/Cable",b:true,lb:false,c:"shoulder_pain",start:"Stand tall, DBs at sides, slight lean, soft elbows.",move:"Raise arms to shoulder height with thumbs slightly lower than pinkies; lower slowly.",avoid:"Shrugging, using momentum, or raising above parallel."},
  // PULL — HORIZONTAL
  {n:"Doorframe Row",p:"Pull Horizontal",t:1,s:"Upper",e:"Doorframe",b:true,lb:false,c:"",start:"Grip doorframe at hip height, arms straight, slight lean back.",move:"Pull body toward doorframe driving elbows back; lower under control.",avoid:"Shrugging or losing rigid body position."},
  {n:"Resistance Band Row",p:"Pull Horizontal",t:1,s:"Upper",e:"Band",b:true,lb:false,c:"",start:"Band anchored at chest height, arms extended.",move:"Drive elbows back to ribcage; squeeze shoulder blades.",avoid:"Shrugging or using torso rotation."},
  {n:"Single-Arm Dumbbell Row",p:"Pull Horizontal",t:2,s:"Upper",e:"Dumbbell/Bench",b:false,lb:false,c:"shoulder_pain",start:"One knee and hand on bench, dumbbell hanging.",move:"Drive elbow back and up to hip, torso square; lower fully.",avoid:"Twisting the torso or shrugging at initiation."},
  {n:"KB One-Leg Row",p:"Pull Horizontal/Single-leg",t:3,s:"Upper",e:"Kettlebell",b:false,lb:false,c:"shoulder_pain,lower_limb_injury",start:"Balance on one leg in a single-leg hip hinge, KB hanging in opposite hand.",move:"Row KB to hip by driving elbow back; maintain single-leg balance and level hips throughout.",avoid:"Using hip rotation to assist the row or dropping the stance leg knee inward."},
  {n:"Cable Seated Row",p:"Pull Horizontal",t:2,s:"Upper",e:"Cable",b:true,lb:false,c:"lower_back_flexion",start:"Seated, feet on platform, slight forward hinge, arms extended.",move:"Drive elbows back to waist, squeeze scapulae; slowly return.",avoid:"Rocking torso or losing hinge position."},
  {n:"Reverse Fly (Machine)",p:"Pull Horizontal/Rear Delt",t:2,s:"Upper",e:"Machine",b:true,lb:false,c:"shoulder_pain,neck_pain",start:"Sit facing the pad, arms forward gripping handles at chest height with slight elbow bend.",move:"Draw handles wide to sides squeezing shoulder blades together; return under control.",avoid:"Shrugging, using momentum, or extending elbows fully during the movement."},
  {n:"Face Pull",p:"Pull Horizontal/Rear Delt",t:2,s:"Upper",e:"Cable",b:true,lb:false,c:"shoulder_pain",start:"Cable at face height, rope attachment, step back.",move:"Pull rope to face splitting at ears; shoulders externally rotate at end range.",avoid:"Pulling toward chest rather than face."},
  {n:"Barbell Bent-Over Row",p:"Pull Horizontal",t:3,s:"Upper",e:"Barbell",b:true,lb:false,c:"lower_back_flexion",start:"Hinge to near-parallel, overhand grip, bar below sternum.",move:"Pull to lower ribcage, retract scapulae; lower under control.",avoid:"Jerking from hip or losing lumbar position under load."},
  // PULL — VERTICAL
  {n:"Lat Pulldown",p:"Pull Vertical",t:1,s:"Upper",e:"Cable Machine",b:true,lb:false,c:"shoulder_pain",start:"Seated, thighs under pads, wide overhand grip, slight lean.",move:"Pull bar to upper chest, drive elbows down and back; control return.",avoid:"Pulling behind neck or using excessive body swing."},
  {n:"TRX / Ring Row",p:"Pull Vertical",t:2,s:"Upper",e:"TRX/Rings",b:true,lb:false,c:"shoulder_pain",start:"Hang under rings or TRX, body at angle, arms extended.",move:"Pull chest to hands, squeeze shoulder blades; lower under control.",avoid:"Hips dropping or elbows flaring wide."},
  {n:"Band-Assisted Pull-Up",p:"Pull Vertical",t:2,s:"Upper",e:"Bar/Band",b:true,lb:false,c:"shoulder_pain",start:"Band under knee, full hang, lats engaged.",move:"Drive elbows to hips, pull chin above bar; lower under control.",avoid:"Swinging or kipping."},
  {n:"Pull-Up",p:"Pull Vertical",t:3,s:"Upper",e:"Pull-up Bar",b:true,lb:false,c:"shoulder_pain",start:"Full hang, overhand grip, lats engaged, core braced.",move:"Drive elbows to hips, pull chin above bar; lower slowly to full hang.",avoid:"Kipping, partial range, or shrugging at top."},
  // CARRY
  {n:"Farmer's Carry",p:"Carry",t:1,s:"Full Body",e:"DB/KB",b:true,lb:true,c:"",start:"Weights at sides, tall posture, shoulders back and down.",move:"Walk with controlled steps maintaining upright torso and braced core.",avoid:"Leaning to one side, shrugging, or overstriding."},
  {n:"Suitcase Carry",p:"Carry/Single-side",t:2,s:"Full Body",e:"DB/KB",b:false,lb:true,c:"",start:"Weight in one hand at side, tall posture.",move:"Walk maintaining level hips and shoulders — resist side bend.",avoid:"Leaning away from weight or hip hiking."},
  {n:"Overhead Carry",p:"Carry/Overhead",t:3,s:"Full Body",e:"DB/KB",b:false,lb:true,c:"shoulder_pain",start:"Weight pressed to lockout overhead, elbow extended, core braced.",move:"Walk with control, weight stacked over shoulder.",avoid:"Elbow bending, ribcage flaring, or torso leaning away."},
  // CORE
  {n:"Supine Knee Hold",p:"Core Anti-Extension",t:1,s:"Core",e:"None",b:true,lb:false,c:"",start:"Lie on back, press lower back to floor, knees at tabletop 90°.",move:"Hold knees at tabletop while breathing steadily; maintain lower back contact with floor.",avoid:"Lower back arching away from floor."},
  {n:"Dead Bug",p:"Core Anti-Extension",t:1,s:"Core",e:"None",b:true,lb:false,c:"lower_back_flexion",start:"On back, arms to ceiling, hips and knees at 90°, lower back on floor.",move:"Lower opposite arm and leg to just above floor; return; alternate.",avoid:"Lower back arching off floor during movement."},
  {n:"Plank (Forearm)",p:"Core Anti-Extension",t:1,s:"Core",e:"None",b:true,lb:false,c:"shoulder_pain",start:"Forearms on floor, elbows under shoulders, rigid line head to heel.",move:"Hold breathing steadily; squeeze glutes and brace midsection.",avoid:"Hips rising or sagging; holding breath."},
  {n:"Bird Dog",p:"Core Anti-Rotation",t:1,s:"Core",e:"None",b:true,lb:false,c:"",start:"All-fours, hands under shoulders, knees under hips, neutral spine.",move:"Extend opposite arm and leg, hold briefly, return with control.",avoid:"Rotating pelvis, hiking a hip, or hyperextending lower back."},
  {n:"Ab Machine",p:"Core Flexion",t:1,s:"Core",e:"Machine",b:true,lb:false,c:"lower_back_flexion,spinal_load",start:"Sit in machine, grip handles at chest, back against pad.",move:"Flex forward through the trunk drawing ribs toward hips; return under control.",avoid:"Pulling with the arms — the movement must come from the abdominals, not the upper body."},
  {n:"Russian Twist",p:"Core Rotation",t:2,s:"Core",e:"None/KB/DB",b:true,lb:false,c:"lower_back_flexion",start:"Sit with knees bent, feet slightly elevated, lean back slightly, weight or hands together at chest.",move:"Rotate torso left and right touching weight (or hands) toward the floor on each side.",avoid:"Rounding excessively through the lower back or rotating from the arms rather than the trunk."},
  {n:"Cable Rotation",p:"Core Anti-Rotation/Dynamic",t:2,s:"Core",e:"Cable",b:true,lb:false,c:"lower_back_flexion",start:"Stand side-on to cable, anchor at chest height, arms extended holding handle in both hands.",move:"Rotate trunk away from cable through controlled range; resist the return.",avoid:"Letting the arms lead rather than the torso; movement comes from trunk rotation, not shoulder swing."},
  {n:"Woodchopper (High to Low)",p:"Core Rotation/Power",t:2,s:"Core",e:"Cable/KB",b:true,lb:false,c:"lower_back_flexion",start:"Stand side-on to high cable or hold KB overhead on one side; feet shoulder-width.",move:"Rotate and pull the weight diagonally down across the body to opposite hip in a chopping motion.",avoid:"Using momentum to swing — control both the drive and the return."},
  {n:"Hollow Body Hold",p:"Core Anti-Extension",t:2,s:"Core",e:"None",b:true,lb:false,c:"lower_back_flexion",start:"Lie on back, press lower back to floor, arms overhead, legs extended.",move:"Lift shoulders and legs slightly off floor, hold the C-shape tension.",avoid:"Arching lower back or holding breath."},
  {n:"Pallof Press",p:"Core Anti-Rotation",t:2,s:"Core",e:"Cable/Band",b:true,lb:false,c:"",start:"Side-on to cable at chest height, hold handle at sternum.",move:"Press handle straight out, hold briefly, return to sternum.",avoid:"Rotating toward or away from cable."},
  {n:"KB Sit-Up",p:"Core Flexion",t:2,s:"Core",e:"Kettlebell",b:true,lb:false,c:"lower_back_flexion,neck_pain",start:"Lie on back, knees bent, holding KB at chest with both hands.",move:"Curl up through the spine to seated, leading with chest; lower under control one vertebra at a time.",avoid:"Jerking with the neck to initiate or using the KB as a counterweight swing."},
  {n:"Ab Wheel Rollout",p:"Core Anti-Extension",t:3,s:"Core",e:"Ab Wheel",b:true,lb:false,c:"lower_back_flexion",start:"Kneel behind wheel, grip handles, hips over knees.",move:"Roll forward until near-parallel; pull back.",avoid:"Lower back sagging at full extension."},
  // SINGLE-LEG / LUNGE
  {n:"Clamshell",p:"Isolation/Hip External Rotation",t:1,s:"Lower",e:"None/Band",b:true,lb:false,c:"",start:"Lie on side, hips and knees bent, band above knees.",move:"Rotate top knee open like a clamshell, feet together; lower slowly.",avoid:"Rocking pelvis backward or lifting top foot."},
  {n:"Side-Lying Hip Abduction",p:"Isolation/Hip Abductor",t:1,s:"Lower",e:"None",b:false,lb:false,c:"",start:"Lie on side, hips stacked, upper leg straight.",move:"Raise upper leg to ~45°, pause, lower with control.",avoid:"Rolling pelvis back or raising beyond pelvic stability."},
  {n:"Step-Up (Low Box)",p:"Single-Leg",t:1,s:"Lower",e:"Step/Low Box",b:false,lb:true,c:"knee_pain",start:"Stand facing a low step, one foot on top.",move:"Drive through elevated heel to stand; lower trail leg under control.",avoid:"Pushing off floor with trail foot."},
  {n:"Reverse Lunge",p:"Single-Leg",t:1,s:"Lower",e:"BW/DB",b:false,lb:true,c:"knee_pain",start:"Stand tall, feet together.",move:"Step back onto ball of foot, lower rear knee toward floor; push off to return.",avoid:"Slamming rear knee or leaning forward."},
  {n:"Hamstring Curl (Machine)",p:"Isolation/Knee Flexion",t:1,s:"Lower",e:"Machine",b:true,lb:false,c:"",start:"Lie prone or seated, pad just above heels, full knee extension.",move:"Curl heels toward glutes through full range; lower slowly.",avoid:"Lifting hips (prone) or using momentum to swing."},
  {n:"Leg Extension (Machine)",p:"Isolation/Knee Extension",t:1,s:"Lower",e:"Machine",b:true,lb:false,c:"knee_pain",start:"Seated, pad just above ankles, back supported, 90° at knee.",move:"Extend to near-full knee extension; lower under slow control.",avoid:"Hyperextending knee at top or back lifting off pad."},
  {n:"Walking Lunge",p:"Single-Leg",t:2,s:"Lower",e:"BW/DB",b:false,lb:true,c:"knee_pain",start:"Stand tall.",move:"Step forward into lunge, lower rear knee, drive off front heel, alternate.",avoid:"Trunk wobble, knee collapse, or momentum."},
  {n:"Step-Up (High Box)",p:"Single-Leg",t:2,s:"Lower",e:"Box/Bench",b:false,lb:true,c:"knee_pain",start:"Stand facing box at knee height.",move:"Drive through elevated heel to stand on box; lower trail leg under control.",avoid:"Pushing off floor with trail foot."},
  {n:"Lateral Lunge",p:"Single-Leg/Lateral",t:2,s:"Lower",e:"BW/DB",b:false,lb:true,c:"knee_pain",start:"Stand tall, feet together.",move:"Step wide to one side, push hips back into that leg; keep opposite leg straight.",avoid:"Inside foot lifting or torso collapsing forward."},
  // ISOLATION / ACCESSORY
  {n:"Bicep Curl (DB/KB)",p:"Isolation/Elbow Flexion",t:1,s:"Upper",e:"DB/KB",b:true,lb:false,c:"",start:"Stand tall, weights at sides, palms forward, elbows fixed.",move:"Curl both weights to shoulder height; lower under control through full range.",avoid:"Swinging torso or elbows drifting forward."},
  {n:"Tricep Pushdown (Cable)",p:"Isolation/Elbow Extension",t:1,s:"Upper",e:"Cable",b:true,lb:false,c:"shoulder_pain",start:"Stand facing cable, elbows at sides and fixed, hands on bar at chest.",move:"Press down to full elbow extension; control return to 90°.",avoid:"Elbows drifting forward or shoulders assisting."},
  {n:"KB Tricep Lift (Overhead)",p:"Isolation/Elbow Extension",t:2,s:"Upper",e:"Kettlebell",b:true,lb:false,c:"shoulder_pain,neck_pain",start:"Hold KB by the bell with both hands, press overhead; elbows pointing forward.",move:"Lower KB behind head by bending elbows; extend back to lockout.",avoid:"Elbows flaring wide or lower back arching to push through the sticking point."},
  {n:"KB Skull Crusher",p:"Isolation/Elbow Extension",t:2,s:"Upper",e:"Kettlebell",b:true,lb:false,c:"shoulder_pain",start:"Lie on back, KB held in both hands extended overhead, elbows vertical.",move:"Lower KB toward forehead by bending elbows only; extend back to lockout.",avoid:"Elbows drifting outward or shoulders rotating during the movement."},
  // KETTLEBELL SPECIFIC
  {n:"KB Halo",p:"Shoulder Mobility/Core",t:1,s:"Upper",e:"Kettlebell",b:true,lb:false,c:"shoulder_pain,neck_pain",start:"Hold KB by horns at chest, feet hip-width, core braced.",move:"Circle KB around the head in both directions, keeping core stable.",avoid:"Arching lower back or losing core tension during the circle."},
  {n:"KB Around the Leg",p:"Coordination/Shoulder",t:2,s:"Full Body",e:"Kettlebell",b:true,lb:false,c:"shoulder_pain",start:"Stand tall, feet hip-width, KB in one hand at side.",move:"Pass KB in a figure-8 or single-leg-circle pattern around one leg, transferring hand to hand.",avoid:"Bending forward excessively or losing controlled pace — the movement should be smooth and deliberate."},
  {n:"KB Swing (Two-Hand)",p:"Hinge/Power",t:2,s:"Full Body",e:"Kettlebell",b:true,lb:true,c:"lower_back_flexion",start:"Feet shoulder-width, KB a foot in front; hinge to grip, hike bell back between legs.",move:"Drive hips forward explosively; KB floats to shoulder height on the momentum.",avoid:"Squatting the swing, using arms to lift, or hyperextending at lockout."},
  {n:"KB Windmill",p:"Lateral Hinge/Core",t:3,s:"Full Body",e:"Kettlebell",b:false,lb:false,c:"shoulder_pain,lower_back_flexion",start:"KB pressed overhead in one arm, feet wide, toes angled away from loaded side.",move:"Hinge to same-side hip, trailing hand slides down inner thigh toward floor; return.",avoid:"Rotating torso instead of a pure lateral hinge — the loaded arm stays vertical."},
  {n:"KB Turkish Get-Up",p:"Full Body/Core",t:3,s:"Full Body",e:"Kettlebell",b:false,lb:true,c:"shoulder_pain,lower_back_flexion",start:"Lie on back, one arm extended with KB locked out, same-side knee bent.",move:"Roll to elbow, press to hand, bridge hips, sweep leg to kneel, stand; reverse the sequence.",avoid:"Losing the locked-out arm overhead at any stage of the movement."},
  {n:"KB Clean",p:"Hinge/Power",t:3,s:"Full Body",e:"Kettlebell",b:false,lb:true,c:"lower_back_flexion",start:"One-hand grip, hike KB back, feet shoulder-width.",move:"Drive hips forward, guide KB in a tight arc close to the body into the rack position on forearm and shoulder.",avoid:"Letting the bell crash onto the forearm; guide it close to the body and thread the hand through at the top."},
  {n:"KB Renegade Row",p:"Pull Horizontal/Core Anti-Rotation",t:3,s:"Full Body",e:"2 Kettlebells",b:true,lb:false,c:"shoulder_pain,wrist_pain",start:"Plank position with hands on KB handles, feet wide, body rigid.",move:"Row one KB to hip keeping hips completely square; lower and repeat other side.",avoid:"Rotating the hips or using a wider stance to compensate for poor core stability."},
  {n:"Dumbbell Front Squat",p:"Squat",t:2,s:"Lower",e:"Dumbbells",b:true,lb:true,c:"knee_pain",start:"Hold dumbbells at shoulders in rack position, elbows high, feet shoulder-width.",move:"Keep elbows up and torso upright; squat until thighs parallel; drive through heels.",avoid:"Dropping elbows or torso tipping forward."},
  {n:"Hack Squat (Machine)",p:"Squat",t:2,s:"Lower",e:"Machine",b:true,lb:true,c:"knee_pain",start:"Shoulders under pads, feet on platform hip-width, toes slightly out.",move:"Lower until thighs are parallel; drive through full foot to extend.",avoid:"Rounding lower back at depth or jerking through the sticking point."},
  {n:"Single-Leg Glute Bridge",p:"Hinge/Single-leg",t:2,s:"Lower",e:"None",b:false,lb:true,c:"",start:"Lie on back, one knee bent foot flat, other leg extended straight to ceiling.",move:"Drive hips up through planted foot to full extension; maintain level hips throughout.",avoid:"Hips rotating or extended leg dropping — keep it level with the planted knee."},
  {n:"Back Extension (Machine)",p:"Hinge/Spinal Extension",t:2,s:"Lower",e:"Machine/GHD",b:true,lb:true,c:"lower_back_flexion,spinal_load",start:"Hips at pad edge, feet hooked under supports, arms crossed at chest.",move:"Hinge forward under control until torso is near vertical; drive back to horizontal using back extensors.",avoid:"Hyperextending past horizontal at the top or rounding aggressively at the bottom."},
  {n:"Incline Dumbbell Press",p:"Push Horizontal",t:2,s:"Upper",e:"DB/Bench",b:true,lb:false,c:"shoulder_pain",start:"Bench at 30-45 degrees, dumbbells at upper chest, feet flat.",move:"Press dumbbells up to full extension with slight inward arc; lower under control.",avoid:"Flaring elbows wider than 70 degrees or arching excessively off the bench."},
  {n:"Arnold Press",p:"Push Vertical",t:2,s:"Upper",e:"Dumbbells",b:true,lb:false,c:"shoulder_pain",start:"Dumbbells in front of face, palms facing you, elbows together at chest height.",move:"Rotate palms forward as you press overhead; reverse the rotation on the way down.",avoid:"Rushing the rotation phase or losing core bracing at the top."},
  {n:"Chin-Up",p:"Pull Vertical",t:3,s:"Upper",e:"Pull-up Bar",b:true,lb:false,c:"shoulder_pain",start:"Full hang, underhand grip shoulder-width, lats engaged.",move:"Pull chest to bar leading with the sternum; lower slowly to full hang.",avoid:"Swinging, using bicep curl initiation only, or not reaching full extension at the bottom."},
  {n:"Cable Straight-Arm Pulldown",p:"Pull Vertical/Isolation",t:2,s:"Upper",e:"Cable",b:true,lb:false,c:"shoulder_pain",start:"Stand facing high cable, overhand grip, arms extended.",move:"With straight arms pull bar to thighs in an arc, squeezing lats at the bottom.",avoid:"Bending the elbows or using torso flexion to assist."},
  {n:"Side Plank",p:"Core Anti-Lateral Flexion",t:2,s:"Core",e:"None",b:false,lb:false,c:"shoulder_pain",start:"Lie on side, elbow under shoulder, feet stacked, body in straight line.",move:"Lift hips off floor to form a rigid diagonal; hold breathing steadily.",avoid:"Hips sagging or rotating forward."},
  {n:"Copenhagen Plank",p:"Core Anti-Lateral/Adductor",t:3,s:"Core",e:"Bench",b:false,lb:false,c:"knee_pain",start:"Side plank with top foot resting on bench, bottom leg extended.",move:"Hold rigid side plank, squeezing inner thigh of top leg into bench.",avoid:"Hips sagging or rotating forward; significantly harder than a standard side plank."},
  {n:"Forward Lunge",p:"Single-Leg",t:2,s:"Lower",e:"BW/DB",b:false,lb:true,c:"knee_pain",start:"Stand tall, feet together.",move:"Step forward, lower rear knee toward floor keeping front shin near-vertical; push off front foot to return.",avoid:"Front knee caving inward or trunk tipping forward."},
  {n:"Donkey Kick",p:"Isolation/Glute",t:1,s:"Lower",e:"None",b:false,lb:false,c:"",start:"All-fours, hands under shoulders, knees under hips, neutral spine.",move:"Drive one heel toward the ceiling keeping knee at 90 degrees; lower under control.",avoid:"Rotating the pelvis or extending the lower back to gain range."},
  {n:"Standing Hip Abduction (Cable/Band)",p:"Isolation/Hip Abductor",t:2,s:"Lower",e:"Cable/Band",b:false,lb:false,c:"lower_limb_injury",start:"Stand side-on to cable or band at ankle height, inside hand on support.",move:"Lift outside leg away from body to 30-45 degrees; lower under control.",avoid:"Leaning trunk toward support side to compensate for hip weakness."},
  // PLYOMETRICS
  {n:"Box Jump",p:"Plyometric/Squat",t:3,s:"Lower",e:"Plyo Box",b:true,lb:true,c:"knee_pain,lower_limb_injury",start:"Stand 1–2 feet from box, athletic stance.",move:"Swing arms, explode through hips and ankles, land softly with bent knees.",avoid:"Landing stiff, stepping down without control, or over-high box."},
  {n:"Jump Squat",p:"Plyometric/Squat",t:3,s:"Lower",e:"None",b:true,lb:true,c:"knee_pain,lower_limb_injury",start:"Feet shoulder-width, squat to parallel.",move:"Explode upward from base, fully extend; land softly.",avoid:"Shallow squat down or landing with loud crash."},
  {n:"Split Jump",p:"Plyometric/Single-leg",t:3,s:"Lower",e:"None",b:false,lb:true,c:"knee_pain,lower_limb_injury",start:"Split stance, rear knee bent.",move:"Explode upward, switch legs in air, land in opposite split and absorb.",avoid:"Knee valgus on landing or landing on toes only."},
];
const staminaEx = [
  {n:"Seated March",p:"Zone 1/Low Impact",t:1,s:"Full Body",e:"Chair",b:true,lb:true,c:"",start:"Sit tall in chair, feet flat, core gently braced.",move:"Lift alternate knees toward chest in a rhythmic march; swing opposite arm naturally.",avoid:"Slumping forward or lifting feet so high posture collapses."},
  {n:"Step-Up Onto Single Step (Rhythmic)",p:"Zone 1–2/Low Impact",t:1,s:"Lower",e:"Single Step",b:true,lb:true,c:"knee_pain",start:"Stand before a single step (approx 10–15cm), hands available for support rail if needed.",move:"Step up and down in a steady rhythm, alternating the lead foot every 10 repetitions; maintain upright posture.",avoid:"Gripping the rail to take weight — hands are for balance safety only, not loading support. See also Strength: Step-Up (Low Box)."},
  {n:"Marching on the Spot (Standing)",p:"Zone 1–2",t:1,s:"Full Body",e:"None",b:true,lb:true,c:"",start:"Stand tall near a wall or chair for support if needed.",move:"Lift alternate knees to hip height in a steady marching rhythm; swing opposite arm.",avoid:"Leaning back or allowing knees to drop below hip height — maintain upright posture throughout."},
  {n:"Brisk Walk",p:"Zone 2",t:1,s:"Full Body",e:"None",b:true,lb:true,c:"",start:"Stand tall, arms relaxed, comfortable footwear.",move:"Walk at pace where you can speak but feel slightly breathless (RPE 3–4).",avoid:"Slumping forward, overstriding, or pace so slow there is no stimulus."},
  {n:"Treadmill Incline Walk",p:"Zone 2",t:1,s:"Full Body",e:"Treadmill",b:true,lb:true,c:"",start:"Set incline 8–12%, brisk walking speed.",move:"Walk steadily, slight forward lean, full push-off through rear foot.",avoid:"Holding handrails to offload the incline."},
  {n:"Stationary Bike (Steady)",p:"Zone 2",t:1,s:"Full Body",e:"Bike",b:true,lb:false,c:"knee_pain",start:"Seat at hip height, slight knee bend at bottom of pedal stroke.",move:"Pedal at 70–90 RPM; RPE 3–4.",avoid:"Bouncing on saddle; drop resistance before raising cadence."},
  {n:"Walk-Run Intervals (1:1)",p:"Zone 2/Intervals",t:1,s:"Full Body",e:"None",b:true,lb:true,c:"",start:"Begin at brisk walk.",move:"Alternate 1 min easy run and 1 min walk; repeat for session duration.",avoid:"Running so fast the walk recovery feels insufficient."},
  {n:"Rowing Machine (Steady)",p:"Zone 2",t:2,s:"Full Body",e:"Rower",b:true,lb:false,c:"lower_back_flexion",start:"Feet strapped, slight forward hinge, arms extended.",move:"Drive with legs first, lean back, pull to lower ribcage; recover in reverse.",avoid:"Initiating pull with arms before legs are fully extended."},
  {n:"Continuous Easy Run",p:"Zone 2",t:2,s:"Full Body",e:"None",b:true,lb:true,c:"lower_limb_injury",start:"Start at fully conversational pace.",move:"Run steadily maintaining nasal breathing or RPE 3–4.",avoid:"Starting too fast; check pace in first 5 minutes."},
  {n:"Stair Climb",p:"Zone 2–3",t:1,s:"Lower",e:"Stairs",b:true,lb:true,c:"knee_pain",start:"Tall posture, hands lightly on rail for safety.",move:"Climb steadily, pushing through full foot on each step.",avoid:"Using handrails to take weight off."},
  {n:"Fartlek Run",p:"Zone 2–4 Mixed",t:2,s:"Full Body",e:"None",b:true,lb:true,c:"lower_limb_injury",start:"Begin at easy conversational run.",move:"Surge to hard effort (RPE 7–8) for 20–60 sec; recover fully.",avoid:"Making all surges the same length."},
  {n:"Tempo Run Intervals (3:1)",p:"Zone 3–4",t:2,s:"Full Body",e:"None",b:true,lb:true,c:"lower_limb_injury",start:"Warm up 5 min at easy pace.",move:"Run 3 min at comfortably hard (RPE 6–7), recover 1 min walk/jog.",avoid:"Recovery intervals becoming too easy."},
  {n:"Sprint Intervals",p:"Zone 5",t:3,s:"Full Body",e:"None",b:true,lb:true,c:"lower_limb_injury",start:"Begin from standing or slow jog.",move:"Accelerate to near-maximal effort 10–30 sec; full recovery between.",avoid:"Starting at max speed without acceleration phase."},
  {n:"Assault Bike Sprint",p:"Zone 5",t:2,s:"Full Body",e:"Assault Bike",b:true,lb:false,c:"shoulder_pain",start:"Seated, hands on handles, feet on pedals.",move:"Push/pull handles and pedal simultaneously at maximal effort.",avoid:"Rocking excessively side to side."},
  {n:"Hill Repeat Run",p:"Zone 4/Power",t:3,s:"Full Body",e:"None",b:true,lb:true,c:"lower_limb_injury",start:"6–8% grade hill; warm up 10 min flat.",move:"Run hard uphill (RPE 8–9) 30–60 sec; walk or jog down.",avoid:"Overstriding uphill; shorten stride and drive with arms."},
  {n:"KB Swing (HIIT)",p:"Zone 3–4/Power",t:2,s:"Full Body",e:"Kettlebell",b:true,lb:true,c:"lower_back_flexion",start:"Two-hand KB swing setup.",move:"Continuous swings at higher cadence; 10–20 reps per interval.",avoid:"Squatting the swing or rushing at expense of hip extension."},
  {n:"Tabata Squat",p:"HIIT/Zone 4",t:1,s:"Lower",e:"None",b:true,lb:true,c:"knee_pain",start:"Feet shoulder-width, arms forward.",move:"20 sec max bodyweight squats / 10 sec rest × 8 rounds.",avoid:"Depth diminishing as fatigue increases."},
  {n:"Burpee",p:"HIIT/Full Body",t:2,s:"Full Body",e:"None",b:true,lb:true,c:"shoulder_pain,wrist_pain",start:"Stand tall.",move:"Crouch, kick back to plank, press-up optional, jump feet in, jump overhead.",avoid:"Sagging in plank or not fully extending on jump."},
  {n:"Skater Jumps",p:"HIIT/Lateral Power",t:2,s:"Lower",e:"None",b:false,lb:true,c:"knee_pain",start:"Athletic stance, slight hinge.",move:"Leap laterally off one foot, land on opposite foot in single-leg hinge; repeat.",avoid:"Landing stiff or with knee valgus."},
];
const coordEx = [
  // STATIC BALANCE
  {n:"Two-Leg Stance (Eyes Open)",p:"Static Balance",t:1,s:"Full Body",e:"None",b:true,lb:false,c:"",start:"Stand tall, feet hip-width, arms at sides. Have a sturdy chair or wall within arm's reach.",move:"Hold 30–60 sec; minimise sway using ankle strategy. Time is the first progression.",avoid:"Gripping floor with toes or leaning on support."},
  {n:"Two-Leg Stance (Eyes Closed)",p:"Static Balance/Sensory",t:1,s:"Full Body",e:"None",b:true,lb:false,c:"",start:"Stand tall, feet hip-width. Have a wall within arm's reach before closing eyes.",move:"Close eyes, hold 20–30 sec; use ankle strategy to control sway.",avoid:"Standing near a hazard — clear the area and have support close before proceeding."},
  {n:"Seated Balance (Unstable)",p:"Static Balance/Seated",t:1,s:"Full Body",e:"Chair",b:true,lb:false,c:"",start:"Sit tall in chair, arms at sides, feet flat.",move:"Lift one foot slightly off floor; hold 10–20 sec; alternate.",avoid:"Gripping chair arms or holding breath."},
  {n:"Narrow Stance Balance",p:"Static Balance",t:1,s:"Full Body",e:"None",b:true,lb:false,c:"",start:"Feet together, arms at sides, eyes open. Have support within arm's reach.",move:"Hold 30–60 sec; progress to eyes closed only when stable with feet together.",avoid:"Widening the base whenever it becomes challenging — maintain the reduced base of support."},
  {n:"Tandem Stance",p:"Static Balance",t:2,s:"Full Body",e:"None",b:true,lb:false,c:"",start:"One foot directly in front of other heel-to-toe. Have support within arm's reach.",move:"Hold 30 sec eyes open; progress to eyes closed only once stable at this base.",avoid:"Arms flying immediately — use a small corrective arm sway to recover rather than grabbing support."},
  {n:"Single-Leg Stance (Eyes Open)",p:"Static Balance",t:2,s:"Full Body",e:"None",b:false,lb:false,c:"lower_limb_injury",start:"Stand on one leg, opposite foot lifted, arms at sides. Have support within reach.",move:"Hold 30 sec; maintain level hips, look straight ahead.",avoid:"Hip dropping on unsupported side."},
  {n:"Single-Leg Stance (Eyes Closed)",p:"Static Balance Advanced",t:3,s:"Full Body",e:"None",b:false,lb:false,c:"lower_limb_injury,fall_risk",start:"Establish single-leg stance eyes open first, then close. Not appropriate for users with fall risk.",move:"Hold 20–30 sec; rely on vestibular and somatosensory feedback.",avoid:"Attempting before single-leg stance eyes open is fully mastered."},
  {n:"Foam Pad Stance (Two-Leg)",p:"Sensory Challenge",t:2,s:"Full Body",e:"Foam Pad",b:true,lb:false,c:"fall_risk",start:"Stand on foam pad, feet hip-width, eyes open. Have support within arm's reach. Not appropriate for those with high fall risk.",move:"Hold 30–60 sec eyes open; progress to eyes closed only when bilateral foam is stable.",avoid:"Gripping toes or compensating with forward lean."},
  {n:"Foam Pad Single-Leg Stance",p:"Sensory Challenge Advanced",t:3,s:"Full Body",e:"Foam Pad",b:false,lb:false,c:"lower_limb_injury,fall_risk",start:"One leg on foam pad, eyes open. For advanced users only — not appropriate for fall risk.",move:"Hold 20–30 sec; control multi-directional sway.",avoid:"Attempting without bilateral foam pad mastery."},
  // DYNAMIC BALANCE
  {n:"Weight Shift (Anterior-Posterior)",p:"Dynamic Balance",t:1,s:"Full Body",e:"None",b:true,lb:false,c:"",start:"Stand tall, feet hip-width. Have support within arm's reach.",move:"Slowly shift weight forward to balls then back to heels; stay within limits of stability.",avoid:"Moving so fast that stepping is required."},
  {n:"Limits of Stability Reach",p:"Dynamic Balance",t:2,s:"Full Body",e:"None",b:true,lb:false,c:"",start:"Stand tall, feet hip-width. Have support within arm's reach.",move:"Reach one arm in each direction — front, side, diagonal — maintain balance without stepping.",avoid:"Moving feet to recover."},
  {n:"Star Excursion Balance",p:"Dynamic Balance",t:2,s:"Full Body",e:"None/Markers",b:false,lb:false,c:"lower_limb_injury",start:"Single-leg stance, reach leg extended. Have support available.",move:"Reach free foot as far as possible while holding stance; return.",avoid:"Hip dropping on reaching side."},
  {n:"Tandem Walk",p:"Gait/Balance",t:2,s:"Full Body",e:"None",b:true,lb:false,c:"fall_risk",start:"Stand at one end of a clear 3m space. Have a wall or rail alongside if available.",move:"Walk heel-to-toe in a straight line; gaze forward at a fixed point ahead.",avoid:"Looking down at feet — use a fixed point ahead. Not T1: requires established bilateral balance first."},
  {n:"Gaze Stability Walk (Head Turns)",p:"Gait/Vestibular",t:2,s:"Full Body",e:"None",b:true,lb:false,c:"vestibular_disorder",start:"Walk at normal pace on clear path with space on both sides.",move:"Turn head left and right every 3–4 steps while maintaining straight walking line.",avoid:"Stopping to turn head; the challenge is head movement during active gait."},
  {n:"Walk and Stop (Rapid)",p:"Gait/Reactive",t:2,s:"Full Body",e:"None",b:true,lb:false,c:"",start:"Walk at normal pace on a clear path.",move:"On self-cue stop immediately and maintain balance; restart.",avoid:"Anticipating the stop by slowing before the cue."},
  // COORDINATION
  {n:"Marching (High Knees, Slow)",p:"Coordination/Gait",t:1,s:"Full Body",e:"None",b:true,lb:false,c:"",start:"Stand tall near support if needed.",move:"Lift alternate knees to hip height in slow deliberate pattern; coordinate with opposite arm swing.",avoid:"Leaning back or losing arm-leg coordination."},
  {n:"Contralateral Arm-Leg Reach",p:"Coordination/Balance",t:1,s:"Full Body",e:"None",b:true,lb:false,c:"",start:"Stand tall, weight on both feet, support within reach.",move:"Reach right arm forward and extend left leg back simultaneously; hold 3 sec; alternate.",avoid:"Rushing; hold each position briefly for motor control benefit."},
  {n:"Ladder Drill — Two-Feet-In",p:"Coordination/Agility",t:2,s:"Full Body",e:"Agility Ladder",b:true,lb:false,c:"fall_risk,non_sport",start:"Stand at one end of ladder. For coordinated, non-fall-risk users interested in sport or agility.",move:"Step both feet into each box progressing forward; accuracy before speed.",avoid:"Rushing before footwork pattern is consistent. Not appropriate for those with fall risk."},
  {n:"Ladder Drill — Lateral Shuffle",p:"Coordination/Agility",t:2,s:"Full Body",e:"Agility Ladder",b:true,lb:false,c:"fall_risk,non_sport",start:"Stand sideways at one end of ladder. For non-fall-risk users only.",move:"Shuffle laterally leading with near foot, both feet in each box.",avoid:"Crossing feet. Not appropriate for fall risk — recommend tandem walk and star excursion first."},
  {n:"Ball Toss Against Wall",p:"Coordination/Gaze",t:1,s:"Upper",e:"Tennis Ball",b:true,lb:false,c:"shoulder_pain",start:"Stand 1–2m from wall, one hand.",move:"Toss ball and catch with same hand; progress to opposite hand.",avoid:"Standing so close difficulty is negligible; increase distance progressively."},
  {n:"Ball Toss (Single-Leg)",p:"Coordination/Dual-task",t:2,s:"Full Body",e:"Tennis Ball",b:false,lb:false,c:"lower_limb_injury",start:"Single-leg stance with support nearby, ball ready.",move:"Toss and catch while maintaining single-leg balance.",avoid:"Placing foot down between catches — work through the instability."},
  {n:"Dual-Task Walk (Cognitive)",p:"Dual-task/Gait",t:2,s:"Full Body",e:"None",b:true,lb:false,c:"",start:"Normal walking pace on clear path.",move:"Walk while counting backwards from 100 in 7s.",avoid:"Stopping to think; the difficulty is maintaining gait quality under cognitive load."},
  {n:"Gaze Stability (x1 Speed)",p:"Vestibular/Gaze",t:1,s:"Full Body",e:"Target Card",b:true,lb:false,c:"vestibular_disorder",start:"Hold letter card at arm's length, seated or standing.",move:"Move head left and right while keeping eyes fixed on target letter.",avoid:"Moving so fast letter blurs — stay at speed where focus is maintained."},
  {n:"Gaze Stability (x2 / Moving Target)",p:"Vestibular Advanced",t:2,s:"Full Body",e:"Target Card",b:true,lb:false,c:"vestibular_disorder",start:"Card moves opposite to head direction.",move:"Head and card move in opposite directions; keep letter in focus.",avoid:"Attempting without static background mastery."},
  {n:"Tai Chi — Wave Hands Like Clouds",p:"Coordination/Flow",t:2,s:"Full Body",e:"None",b:true,lb:false,c:"",start:"Shoulder-width stance, arms relaxed.",move:"Shift weight laterally while circling arms in wave pattern; slow and continuous.",avoid:"Rushing — benefit is from slow deliberate motion."},
];
const flexEx = [
  // YOGA / MOBILITY
  {n:"Child's Pose",p:"Restoration/Hip",t:1,s:"Full Body",e:"Mat",b:true,lb:false,c:"knee_pain",start:"Kneel, big toes touching, knees wide, sit back toward heels.",move:"Walk hands forward, forehead to mat; breathe deeply into back.",avoid:"Forcing hips to heels with knee pain; use blanket under knees."},
  {n:"Cat-Cow",p:"Spinal Mobility",t:1,s:"Core",e:"Mat",b:true,lb:false,c:"",start:"All-fours, neutral spine.",move:"Inhale: drop belly, lift head and tail (cow). Exhale: round spine, tuck chin and tail (cat).",avoid:"Rushing; let breath drive the movement."},
  {n:"Downward Facing Dog",p:"Full Body Stretch",t:1,s:"Full Body",e:"Mat",b:true,lb:false,c:"shoulder_pain,wrist_pain",start:"All-fours, tuck toes, push hips up and back to inverted V.",move:"Press through full palm, lengthen spine, pedal heels to warm up.",avoid:"Rounding upper back or locking elbows."},
  {n:"Bridge Pose",p:"Backbend Entry/Glute",t:1,s:"Lower",e:"Mat",b:true,lb:true,c:"",start:"Lie on back, knees bent, feet flat, arms at sides.",move:"Press through feet to lift hips, clasp hands under back.",avoid:"Squeezing glutes so hard the breath is blocked."},
  {n:"Seated Forward Fold",p:"Hamstring/Posterior",t:1,s:"Lower",e:"Mat",b:true,lb:false,c:"lower_back_flexion",start:"Sit with legs extended, tall spine.",move:"Hinge from hips, walk hands down legs; hold.",avoid:"Rounding aggressively from lower back — hinge first."},
  {n:"Supine Spinal Twist",p:"Rotation/Spine",t:1,s:"Core",e:"Mat",b:true,lb:false,c:"spinal_load",start:"Lie on back, one knee to chest, arms wide.",move:"Guide knee across body to opposite side; hold and breathe.",avoid:"Forcing shoulder off floor; block under knee if needed."},
  {n:"Hip Flexor Stretch (Kneeling)",p:"Mobility/Hip Flexor",t:1,s:"Lower",e:"Mat",b:false,lb:false,c:"knee_pain",start:"Kneeling lunge, rear knee down, front foot flat.",move:"Drive hips forward gently; tall spine; hold 30–60 sec each side.",avoid:"Arching lower back to gain range — tuck pelvis slightly."},
  {n:"Thoracic Rotation (Seated)",p:"Mobility/Spinal Rotation",t:1,s:"Core",e:"Chair",b:true,lb:false,c:"",start:"Sit tall, arms crossed on chest.",move:"Rotate upper body left and right through comfortable range; slow.",avoid:"Rotating from lower back."},
  {n:"Ankle Circles and Dorsiflexion",p:"Mobility/Ankle",t:1,s:"Lower",e:"None",b:true,lb:false,c:"",start:"Seated or lying, leg extended.",move:"Circle foot 10× each direction; flex and point repeatedly.",avoid:"Compensating with hip or knee movement."},
  {n:"Foam Roller — Thoracic Spine",p:"Self-Myofascial Release",t:1,s:"Core",e:"Foam Roller",b:true,lb:false,c:"spinal_load",start:"Roller across upper back, hands behind head, knees bent.",move:"Gently extend over roller, breathe out; roll slowly up to shoulders.",avoid:"Rolling lower back — stay above base of ribcage."},
  {n:"Dynamic Hip Circles",p:"Mobility/Hip",t:1,s:"Lower",e:"None",b:true,lb:false,c:"hip_pain",start:"Stand tall, hands on hips.",move:"Draw large circles with each hip in both directions; slow and controlled.",avoid:"Relying on momentum; control the full circle."},
  {n:"Lat Stretch (Doorframe)",p:"Mobility/Shoulder/Lat",t:1,s:"Upper",e:"Doorframe",b:true,lb:false,c:"shoulder_pain",start:"Hold doorframe at arm's length, step back slightly.",move:"Sink hips back and down to create stretch through side and lat; hold.",avoid:"Rounding forward; keep spine long."},
  {n:"World's Greatest Stretch",p:"Mobility/Full Body",t:2,s:"Full Body",e:"None",b:false,lb:false,c:"lower_back_flexion",start:"Lunge position, both hands inside front foot.",move:"Rotate top arm to ceiling, opening chest; alternate and flow.",avoid:"Rushing; spend 2–3 breaths in each position."},
  {n:"Pigeon Pose",p:"Hip Mobility",t:2,s:"Lower",e:"Mat",b:false,lb:false,c:"knee_pain",start:"From downward dog, bring one knee forward toward same-side wrist.",move:"Lower hips toward floor, fold torso over front shin; breathe deeply.",avoid:"Forcing shin parallel if hip mobility is limited."},
  {n:"Warrior I",p:"Standing/Hip",t:2,s:"Full Body",e:"Mat",b:false,lb:true,c:"knee_pain",start:"Rear foot at 45°, front knee over ankle, hips squared.",move:"Raise arms overhead, breathe and hold.",avoid:"Front knee collapsing inward or rear heel lifting."},
  {n:"Warrior II",p:"Standing/Hip",t:2,s:"Full Body",e:"Mat",b:false,lb:true,c:"knee_pain",start:"Wide stance, front foot forward, rear foot at 90°.",move:"Bend front knee over ankle, gaze over front fingers; hold.",avoid:"Leaning torso over front leg or knee caving."},
  {n:"Sun Salutation A",p:"Flow",t:2,s:"Full Body",e:"Mat",b:true,lb:false,c:"shoulder_pain,wrist_pain",start:"Stand at top of mat, feet together, hands at heart.",move:"Flow: mountain → fold → half lift → plank → chaturanga → up dog → down dog → forward.",avoid:"Dropping into chaturanga without shoulder and core control."},
  {n:"Yin Hip Opener (Dragon)",p:"Deep Hip/Flexor",t:2,s:"Lower",e:"Mat",b:false,lb:false,c:"knee_pain",start:"Low lunge, back knee down, front foot forward.",move:"Sink hips low; hold 2–5 minutes breathing steadily.",avoid:"Sharp pain in front knee; reduce depth and support with block."},
  // 34 CLASSICAL PILATES MAT EXERCISES (Joseph Pilates sequence)
  {n:"Pilates Hundred",p:"Core/Stamina",t:2,s:"Core",e:"Mat",b:true,lb:false,c:"neck_pain,shoulder_pain",start:"Lie on back, knees at tabletop or 45°, head lifted, arms by sides.",move:"Pump arms vigorously: inhale 5 counts, exhale 5 counts — 10 rounds = 100 pumps.",avoid:"Lower back arching off mat or neck straining — keep chin slightly tucked."},
  {n:"Pilates Roll Up",p:"Spinal Articulation",t:2,s:"Core",e:"Mat",b:true,lb:false,c:"neck_pain,lower_back_flexion",start:"Lie flat, legs together, arms overhead, palms forward.",move:"Inhale reach arms forward; exhale peel spine off mat one vertebra at a time, reaching crown toward knees.",avoid:"Using momentum or pulling on neck — bend knees if too challenging."},
  {n:"Pilates Roll Over",p:"Spinal Articulation/Inversion",t:3,s:"Core",e:"Mat",b:true,lb:false,c:"neck_pain,spinal_load,osteoporosis",start:"Lie on back, legs together, arms by sides pressing down.",move:"Lift legs to 90°; reach up and over until parallel to floor; slowly lower one vertebra at a time.",avoid:"Rolling onto neck — go no further than upper shoulders."},
  {n:"Pilates One Leg Circles",p:"Hip Mobility/Core",t:1,s:"Lower",e:"Mat",b:false,lb:false,c:"lower_back_flexion",start:"Lie on back, one leg straight on mat with foot flexed, other leg up toward ceiling.",move:"Circle top leg across body, down, and around keeping pelvis stable; 5 circles each direction.",avoid:"Pelvis rocking — keep the lower back grounded throughout."},
  {n:"Pilates Rolling Back",p:"Spinal Massage/Core",t:2,s:"Core",e:"Mat",b:true,lb:false,c:"neck_pain,spinal_load",start:"Sit with knees bent, feet flat; hold front of knees; forehead toward knees in tight C-curve.",move:"Roll back to tips of shoulder blades; use abdominals as the brake to return to balance.",avoid:"Rolling onto neck or using momentum rather than abdominal control."},
  {n:"Pilates One Leg Stretch",p:"Core/Coordination",t:2,s:"Core",e:"Mat",b:true,lb:false,c:"neck_pain,lower_back_flexion",start:"Lie on back, head and shoulders lifted; both knees to chest.",move:"Extend one leg at 45° while both hands hold opposite shin; switch in scissor rhythm.",avoid:"Arching lower back or dropping head between reps."},
  {n:"Pilates Double Leg Stretch",p:"Core",t:2,s:"Core",e:"Mat",b:true,lb:false,c:"neck_pain,lower_back_flexion",start:"Lie on back, head and shoulders lifted, knees hugged to chest.",move:"Extend arms overhead and legs out simultaneously; circle arms back to hug knees in.",avoid:"Lower back arching off mat during the extension phase."},
  {n:"Pilates Spine Stretch Forward",p:"Spinal Mobility/Hamstring",t:1,s:"Core",e:"Mat",b:true,lb:false,c:"lower_back_flexion",start:"Sit tall, legs apart, feet flexed, arms forward at shoulder height.",move:"Exhale: round spine forward reaching past feet; inhale to sit tall stacking spine.",avoid:"Collapsing from lower back — lead with the head and upper spine."},
  {n:"Pilates Rocker with Open Legs",p:"Balance/Core",t:2,s:"Core",e:"Mat",b:true,lb:false,c:"lower_back_flexion,neck_pain",start:"Balance on sit bones, knees bent, hands around ankles; straighten legs to V-position.",move:"Tip pubic bone toward nose to initiate controlled rock back to shoulder blades; return to balance.",avoid:"Rolling onto neck or losing the V position during the rock."},
  {n:"Pilates Corkscrew",p:"Spinal Articulation/Core",t:3,s:"Core",e:"Mat",b:true,lb:false,c:"lower_back_flexion,neck_pain,spinal_load",start:"Lie on back, arms pressing into mat, legs straight to ceiling.",move:"Roll over bringing legs parallel; shift legs right, roll down right side, circle around and up through left.",avoid:"Losing pelvic control during the circle — shoulders stay on mat."},
  {n:"Pilates Saw",p:"Rotation/Hamstring",t:2,s:"Core",e:"Mat",b:true,lb:false,c:"lower_back_flexion",start:"Sit tall, legs wide, feet flexed; arms extended wide at shoulder height.",move:"Inhale grow tall; exhale rotate and reach outside hand toward opposite little toe, pulsing 3×; return.",avoid:"Collapsing through the side — maintain length as you rotate."},
  {n:"Pilates Swan Dive",p:"Spinal Extension/Back Strength",t:3,s:"Full Body",e:"Mat",b:true,lb:false,c:"lower_back_flexion,neck_pain",start:"Lie on stomach, hands by shoulders; lift abs from floor, press to Swan (long spine).",move:"Release arms to sides as body rocks forward; arc position maintained — legs lift as chest lowers, rock back lifting chest.",avoid:"Collapsing the arc shape or using neck to initiate."},
  {n:"Pilates One Leg Kick",p:"Posterior Chain/Hamstring",t:2,s:"Lower",e:"Mat",b:false,lb:false,c:"lower_back_flexion,neck_pain",start:"Lie on stomach propped on forearms, elbows under shoulders, legs straight.",move:"Kick one heel toward seat twice, extend leg straight; switch legs.",avoid:"Lower back collapsing or hips rotating during the kick."},
  {n:"Pilates Double Leg Kick",p:"Posterior Chain/Back Extension",t:2,s:"Full Body",e:"Mat",b:true,lb:false,c:"lower_back_flexion,neck_pain",start:"Lie on stomach, head turned to one cheek; hands clasped high on back, elbows toward mat.",move:"Kick both heels to seat 3×; then extend legs straight while hands reach toward feet and chest lifts.",avoid:"Using neck to initiate the lift or arching lower back excessively."},
  {n:"Pilates Neck Pull",p:"Core/Spinal Articulation",t:3,s:"Core",e:"Mat",b:true,lb:false,c:"neck_pain,lower_back_flexion",start:"Lie on back, legs together, both hands at base of neck; elbows wide.",move:"Inhale lift head and shoulders; exhale roll up bringing crown toward knees; inhale stack to seated; exhale round down.",avoid:"Pulling on the neck with the hands — they support; the abdominals do the work."},
  {n:"Pilates Scissors",p:"Hip Flexibility/Core",t:3,s:"Core",e:"Mat",b:true,lb:false,c:"neck_pain,lower_back_flexion",start:"Lie on back, roll through spine to hands supporting lower back; both legs straight toward ceiling.",move:"Lower one straight leg toward mat while drawing the other toward chest; pulse twice; switch.",avoid:"Losing the supported pelvis position or bending knees during the switch."},
  {n:"Pilates Bicycle",p:"Spinal Mobility/Core",t:3,s:"Core",e:"Mat",b:true,lb:false,c:"neck_pain,spinal_load,osteoporosis",start:"Lie on back, peel spine off floor; hands support pelvis; legs split straight.",move:"Bend front knee toward face; extend and pedal forward; switch directions smoothly.",avoid:"Neck strain or losing the supported position under load."},
  {n:"Pilates Shoulder Bridge",p:"Glute/Hamstring",t:2,s:"Lower",e:"Mat",b:false,lb:true,c:"neck_pain",start:"Lie on back, knees bent, feet hip-width; peel spine off mat to bridge.",move:"Extend one leg to ceiling; lower toward floor with flexed foot; return to ceiling; switch legs.",avoid:"Lower back arching or standing knee shifting inward."},
  {n:"Pilates Spine Twist",p:"Rotation/Core",t:2,s:"Core",e:"Mat",b:true,lb:false,c:"lower_back_flexion",start:"Sit tall, legs together extended, feet flexed; arms wide at shoulder height.",move:"Inhale grow tall; exhale twist to right pulsing twice; return; repeat left.",avoid:"Collapsing forward — grow taller on each twist."},
  {n:"Pilates Jack Knife",p:"Spinal Articulation/Core",t:3,s:"Core",e:"Mat",b:true,lb:false,c:"neck_pain,spinal_load,osteoporosis",start:"Lie on back, arms pressing down by sides, legs together to ceiling.",move:"Draw abs in and roll over; maintaining lifted pelvis, reach legs straight toward ceiling; articulate down.",avoid:"Rolling onto neck or using momentum rather than abdominal control."},
  {n:"Pilates Side Kick",p:"Hip/Glute/Core Stability",t:2,s:"Lower",e:"Mat",b:false,lb:false,c:"neck_pain",start:"Lie on side, body in straight line; head propped on hand; top hand on mat; legs slightly forward.",move:"Lift top leg and kick forward twice with a pulse; lengthen and sweep it back; maintain stable torso.",avoid:"Rolling the pelvis forward or back during the kick — all movement is the leg."},
  {n:"Pilates Teaser",p:"Core/Balance",t:3,s:"Core",e:"Mat",b:true,lb:false,c:"lower_back_flexion,spinal_load",start:"Lie on back, hips and knees at 90°; arms behind head.",move:"Inhale lift arms toward legs while straightening legs and lifting head — form a V; exhale; return.",avoid:"Momentum to get up; modify with bent knees if needed."},
  {n:"Pilates Hip Twist",p:"Core/Hip Stability",t:3,s:"Core",e:"Mat",b:true,lb:false,c:"shoulder_pain,wrist_pain",start:"Sit tall, legs straight and together; hands on floor behind, fingers pointing away.",move:"Float both legs to Teaser position; circle legs right, down, around, back; reverse.",avoid:"Shifting weight into wrists — keep core engaged as the primary stabiliser."},
  {n:"Pilates Swimming",p:"Posterior Chain/Coordination",t:2,s:"Full Body",e:"Mat",b:true,lb:false,c:"neck_pain",start:"Lie on belly, arms extended overhead, legs together; pull navel off mat.",move:"Lift upper back slightly; lift right arm and left leg; alternate rapidly in swimming pattern.",avoid:"Jerking or compressing the neck — gaze stays down."},
  {n:"Pilates Leg Pull Front",p:"Core/Shoulder Stability",t:3,s:"Full Body",e:"Mat",b:true,lb:false,c:"shoulder_pain,wrist_pain,neck_pain",start:"High plank from knees or full extension; shoulders over wrists; body in one line.",move:"Extend one leg up without rotating hips; return to mat; alternate.",avoid:"Hips rotating or lower back sagging during the leg lift."},
  {n:"Pilates Leg Pull",p:"Core/Hip Flexor Strength",t:3,s:"Full Body",e:"Mat",b:true,lb:false,c:"shoulder_pain,wrist_pain,neck_pain",start:"Sit with legs crossed; hands behind back fingers toward body; extend legs and lift hips.",move:"Lift right leg up and down; then left; engage inner thighs and lower abs throughout.",avoid:"Collapsing into the wrists — press actively through the palms."},
  {n:"Pilates Side Kick Kneeling",p:"Hip/Glute/Balance",t:3,s:"Lower",e:"Mat",b:false,lb:false,c:"knee_pain",start:"Kneel on one knee, hand below same shoulder; opposite knee in line with foot; hand behind head.",move:"Kick top leg forward and back while keeping torso completely stable; repeat then switch sides.",avoid:"Side-bending through the torso during the kick — all movement is the leg."},
  {n:"Pilates Side Bend",p:"Lateral Core/Shoulder",t:3,s:"Core",e:"Mat",b:true,lb:false,c:"shoulder_pain,wrist_pain",start:"Sit sideways, legs bent to one side; supporting hand below shoulder.",move:"Press into supporting hand and straighten legs to lift pelvis, making a rainbow arc with body.",avoid:"Collapsing the supporting shoulder — press actively through the palm."},
  {n:"Pilates Boomerang",p:"Full Body Integration",t:3,s:"Full Body",e:"Mat",b:true,lb:false,c:"neck_pain,spinal_load,osteoporosis",start:"Sit tall, legs extended, right ankle over left; palms by hips.",move:"Lift legs, rollover, switch ankle cross, roll down to Teaser balance; clasp hands behind; lower legs; circle arms to ankles; roll to sit.",avoid:"Rolling onto neck or losing control of the momentum — this is an advanced sequence."},
  {n:"Pilates Seal",p:"Spinal Massage/Balance",t:2,s:"Core",e:"Mat",b:true,lb:false,c:"neck_pain,spinal_load",start:"Sit with hips close to heels, knees bent wide; lace hands between legs, hold outer ankles; feet together.",move:"Make C-curve; clap feet 3×; roll back to shoulder blades; clap feet 3×; roll back to balance.",avoid:"Rolling onto neck or releasing the C-curve."},
  {n:"Pilates Crab",p:"Spinal Mobility/Core",t:3,s:"Core",e:"Mat",b:true,lb:false,c:"neck_pain,spinal_load",start:"Sit with legs crossed; hold feet; tilt pelvis with posterior pelvic tilt.",move:"Roll back maintaining leg position and C-curve to tops of shoulders; return to balance without feet touching.",avoid:"Rolling onto neck or releasing the leg position during the roll."},
  {n:"Pilates Rocking",p:"Back Extension/Mobility",t:3,s:"Full Body",e:"Mat",b:true,lb:false,c:"lower_back_flexion,neck_pain,shoulder_pain",start:"Lie on stomach; bend knees and hold both ankles; press ankles into hands.",move:"Lift chest and knees by engaging back extensors; maintain arc and rock forward and back.",avoid:"Releasing the arc shape or using arms rather than back extensors to lift."},
  {n:"Pilates Control Balance",p:"Core/Hip Flexibility",t:3,s:"Full Body",e:"Mat",b:true,lb:false,c:"neck_pain,spinal_load,osteoporosis",start:"Lie on back, roll over and place balls of feet on mat; circle arms around to hold one ankle.",move:"Extend opposite leg up; without changing hips, switch — place that foot down, extend other leg up.",avoid:"Losing pelvic position during the switch or bearing weight on the neck."},
  {n:"Pilates Push Up",p:"Push/Core Integration",t:2,s:"Upper",e:"Mat",b:true,lb:false,c:"shoulder_pain,wrist_pain",start:"Stand with feet together; roll down through spine to hands on mat; walk hands to plank.",move:"Bend elbows toward ribs in a tricep press-up ×5; lift pelvis; walk hands to feet; roll up to standing.",avoid:"Losing the plank position or arching lower back during the press-up portion."},
];

// ── MAP DOMAIN ──────────────────────────────────────────────────────────────
const domainMap = [
  { data: strengthEx, domain: 'strength' },
  { data: staminaEx,  domain: 'stamina' },
  { data: coordEx,    domain: 'coordination' },
  { data: flexEx,     domain: 'flexibility' },
];

// ── SEGMENT NORMALISER ───────────────────────────────────────────────────────
function normaliseSegment(s) {
  const map = {
    'lower':     'lower',
    'upper':     'upper',
    'full body': 'full_body',
    'full_body': 'full_body',
    'core':      'core',
  };
  return map[s.toLowerCase()] || 'full_body';
}

// ── SENSIBLE DEFAULTS BY DOMAIN ──────────────────────────────────────────────
function getDefaults(domain) {
  if (domain === 'coordination') return { sets: 3, reps_min: 1, reps_max: 1, rest: 30 };
  if (domain === 'flexibility')  return { sets: 1, reps_min: 1, reps_max: 1, rest: 0 };
  return { sets: 3, reps_min: 8, reps_max: 12, rest: 90 };
}

// ── BUILD ROWS ───────────────────────────────────────────────────────────────
const allRows = [];
for (const { data, domain } of domainMap) {
  const def = getDefaults(domain);
  for (const ex of data) {
    allRows.push({
      name:              ex.n,
      domain,
      movement_pattern:  ex.p,
      tier:              ex.t,
      segment:           normaliseSegment(ex.s),
      equipment:         ex.e,
      bilateral:         ex.b,
      load_bearing:      ex.lb,
      contraindications: ex.c || '',
      technique_start:   ex.start,
      technique_move:    ex.move,
      technique_avoid:   ex.avoid,
      gif_search_name:   ex.n,
      default_sets:      def.sets,
      default_reps_min:  def.reps_min,
      default_reps_max:  def.reps_max,
      default_rest_secs: def.rest,
    });
  }
}

// ── SEED ─────────────────────────────────────────────────────────────────────
async function seed() {
  console.log(`Seeding ${allRows.length} exercises...`);

  // Clear existing
  const { error: delErr } = await supabase.from('alongside_exercises').delete().neq('id', '00000000-0000-0000-0000-000000000000');
  if (delErr) { console.error('Delete failed:', delErr.message); process.exit(1); }
  console.log('Cleared existing rows.');

  // Insert in batches of 50
  const BATCH = 50;
  let inserted = 0;
  for (let i = 0; i < allRows.length; i += BATCH) {
    const batch = allRows.slice(i, i + BATCH);
    const { data, error } = await supabase.from('alongside_exercises').insert(batch).select('id');
    if (error) {
      console.error(`Batch ${Math.floor(i/BATCH)+1} failed:`, error.message);
      process.exit(1);
    }
    inserted += data.length;
    console.log(`Batch ${Math.floor(i/BATCH)+1}: inserted ${data.length} rows (total: ${inserted})`);
  }

  console.log(`
Seeding complete. ${inserted} exercises inserted.`);
  if (inserted !== allRows.length) {
    console.warn(`WARNING: Expected ${allRows.length}, got ${inserted}`);
    process.exit(1);
  }
  process.exit(0);
}

seed().catch(err => { console.error('Unexpected error:', err); process.exit(1); })

seed().catch(err => { console.error(err); process.exit(1); });
